### PR TITLE
New CI image; target caching

### PR DESCRIPTION
**Pull request by TriplEight**
New CI image; 
target caching

### CODE REVIEW

**Comment by sjeohp** [comment]
@TriplEight could you please add a description and comment on the status (ready for merge or not)

**Comment by TriplEight** [comment]
Ready to merge

**Comment by sjeohp** [comment]
[failed dockerize in staging](https://gitlab.parity.io/parity/parity-processbot/-/jobs/573837)

**Comment by TriplEight** [comment]
@sjeohp please try in with a tag/on a protected branch, must work now

**Comment by sjeohp** [comment]
bot merge

**Comment by sjeohp** [comment]
bot merge

**Pull request merged**
