### PR TITLE
Fix rebase command

### LINKED ISSUE #339: Acknowledge commands
When CI is stuck on pending statuses for a long time, such as https://github.com/paritytech/substrate/pull/9976, the bot right now stays silent. processbot [could do as dependabot does and react with a "thumbs up" reaction](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/managing-pull-requests-for-dependency-updates#managing-dependabot-pull-requests-with-comment-commands) which seems overall cleaner than posting a comment on the pull request's thread.

### LINKED ISSUE #385: "bot rebase" is broken / improve messaging when branch is up-to-date
https://github.com/paritytech/substrate/pull/11448#issuecomment-1130064401

https://github.com/paritytech/parity-processbot/issues/385#issuecomment-1130176317

### PR DESCRIPTION
**Pull request by joao-paulo-parity**
\+ acknowledge commands

close #339 
close #385

### CODE REVIEW

**Comment by mordamax** [comment]
makes sense to add rebase tests?

**Comment by koenw** [comment]
> makes sense to add rebase tests?

This fix comes with a (very reasonable) refactor, but combined with how Github shows diffs that does make it harder to at a glance notice what exactly you have fixed. This highlights for me that indeed it would be nice to have tests here, especially since operations like rebasing are based on external state and thus the compiler can't help us find mistakes here. However, I also think writing these tests will be an investment that perhaps only make sense if we want to continue supporting processbot, so perhaps we should make a choice there first.

I now also realize this change has to do more with error reporting than git operations. I don't see any glaring mistakes and I have faith in JP and the compiler, so I won't do a in-depth review, but if this PR would've been broken up in more functional pieces (e.g. one for formatting, one for the fix and one for refactor) that would have made it easier to validate.

**Review by koenw — APPROVED** [review]
I would've like multiple PR

**Comment by joao-paulo-parity** [comment]
> makes sense to add rebase tests?

possibly as a new item in https://github.com/paritytech/parity-processbot/issues/353, but we have more important things to test IMO first. I don't intend to add tests here.

**Comment by joao-paulo-parity** [comment]
> This fix comes with a (very reasonable) refactor, but combined with how Github shows diffs that does make it harder to at a glance notice what exactly you have fixed.

I didn't intend to refactor, in the sense of making things "nicer", purposefully. Most of the diff size is due to extracting the reusable part of `update_pr_branch` (basically the start) to a `setup_contributor_branch` function which is used for the current rebase feature + `update_pr_branch`. After I did that, I found out that I also had to update `src/shell.rs` and a few other places due to this extraction. In the end it did end up being a refactor but it was based around the needs of extracting parts of `update_pr_branch` into `setup_contributor_branch`, not because I compusively wanted to refactor the code. Sorry if it made the change harder to follow.

**Comment by joao-paulo-parity** [comment]
demoed in https://github.com/paritytech/main-for-processbot-staging/pull/57

**Pull request merged**
